---

- name: Deploying new application code to a cluster of video players.

  hosts: players
  remote_user: pi
  sudo: yes
  vars:
    app_dir: /app

  tasks:
  - name: 'Create app directory'
    file: path={{ app_dir }}
          owner={{ ansible_ssh_user }}
          state=directory

  - name: 'Deploy app'
    git: repo=https://github.com/heisters/node-omxplayer-sync.git
         dest={{ app_dir }}
    sudo: no

  - name: 'Install app dependencies'
    npm: path={{ app_dir }} production=yes state=present
    sudo: no

  - name: 'Start service'
    service: name=video-player state=restarted
