---
- name: 'Update APT package cache'
  apt: update_cache=yes

- name: 'Upgrade APT to the lastest packages'
  apt: upgrade=safe

- name: 'Create local tmp dir'
  local_action: file path={{ role_path }}/files/tmp state=directory
  sudo: no

- name: 'Fetch latest omxplayer'
  local_action: get_url url={{ omxplayer_url }}
                        dest={{ role_path }}/files/tmp/omxplayer.deb
                        sha256sum={{ omxplayer_sha }}
  sudo: no

- name: 'Copy omxplayer'
  copy: src=tmp/omxplayer.deb dest=/tmp/omxplayer.deb

- name: 'Install omxplayer dependencies'
  apt: name={{ item }} state=present
  with_items:
    - libpcre3
    - fonts-freefont-ttf
    - fbset

- name: 'Install dbus dependencies'
  apt: name={{ item }} state=present
  with_items:
    - libdbus-1-dev
    - libglib2.0-dev
    - libexpat1
    - libexpat1-dev

- name: 'Install omxplayer'
  apt: deb=/tmp/omxplayer.deb

- name: 'Install forever'
  npm: name=forever global=yes production=yes state=present

- name: 'Create service configuration'
  template: src=sysinitv.sh dest=/etc/init.d/video-player mode="0755"

- name: 'Setup service'
  service: name=video-player enabled=yes


- name: 'Install iptables-persistent'
  apt: name=iptables-persistent state=present

- name: 'Check if port 80 redirection is enabled'
  shell: iptables -L -t nat | grep -q "http redir ports 8080"
  register: check_redir_http
  ignore_errors: yes
  changed_when: no
  always_run: yes

- name: 'Redirect port 80'
  command: iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080
  when: check_redir_http.rc != 0
  notify: 'Save iptables'
