#!/usr/bin/env bash

if [ "$1" == "" ] || [ "$2" == "" ]; then
  echo "usage: $0 [disk] [image]"
  exit 1
fi

if [ ! -b "$1" ]; then
  echo "$1 does not appear to be a valid disk identifier"
  exit 2
fi

if [ ! -f "$2" ]; then
  echo "$2 does not appear to be a valid file"
  exit 2
fi

disk="$1"
rdisk=$(echo "$disk" | sed 's/disk\([0-9]\)s[0-9]/rdisk\1/')
image="$2"

read -p "Unmounting ${disk} and writing ${image} to ${rdisk}. Press y to continue. " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
  echo "aborting."
  exit 1
fi

sudo diskutil unmount "$disk"
sudo dd bs=1m if="$image" of="$rdisk"
sudo diskutil eject "$rdisk"
echo "${image} written to ${rdisk}. It is safe to remove the card."

